config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  get 'cookiegram/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get  '/signup',  to: 'users#new'
  get  '/login',   to: 'sessions#new'
  post '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  resources :users
  resources :posts do
    resources :comments
  end

  root 'cookiegram#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  validates :description, presence: true,
            length: { minimum: 1 }
  validates :image, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  VALID_USERNAME_REGEX = /\A([A-z\-])+\z/i

  before_save do
    self.email = email.downcase
    self.username = username.downcase
  end

  has_many :posts, dependent: :destroy
  has_many :comments, through: :posts
  validates :description, presence: true,
            length: { minimum: 3, maximum: 255 }
  validates :email, presence: true,
           uniqueness: { case_sensitive: false },
           format: { with: VALID_EMAIL_REGEX },
           length: { minimum: 3, maximum: 50 }
  validates :username, presence: true,
            uniqueness: { case_sensitive: false },
            format: { with: VALID_USERNAME_REGEX },
            length: { minimum: 3, maximum: 50 }
  validates :image, presence: true,
            length: { minimum: 3 }

  has_secure_password

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  include SessionsHelper

  def create
    if is_logged_in?
      @post = Post.find(params[:post_id])
      @comment = Comment.new({
          post: @post,
          message: params[:comment][:message],
          user: @current_user
      })

      if @comment.save
        redirect_to @post
      else
        render 'new'
      end
    else
      render 'new'
    end
  end

end

app/controllers/cookiegram_controller.rb
class CookiegramController < ApplicationController
  def index
    @posts = Post.all
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  include SessionsHelper

  def new
    @post = Post.new
  end

  def edit
    @post = Post.find(params[:id])
  end

  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
    puts "Hey"
    puts @post.comments.size
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to @post
    else
      render 'new'
    end
  end

  def update
    @post = Post.find(params[:id])

    if @post.update(post_params)
      redirect_to @post
    else
      render 'edit'
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path
  end

  private
  def post_params
    if is_logged_in?
      {
        description: params[:post][:description],
        image: params[:post][:image],
        user: @current_user
      }
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  protect_from_forgery with: :exception
  include SessionsHelper

  def new

  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to user
    else
      flash.now[:danger] = 'Invalid email, username or password'
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include SessionsHelper

  def new
    @user = User.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def show
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)
    @user.description = "I love cookies!"
    @user.image = "https://awesomepicture.com"
    if @user.save
      log_in @user
      redirect_to @user
    else
      render 'new'
    end
  end

  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy

    redirect_to users_path
  end

  private
  def user_params
    params.require(:user).permit(:username, :email, :password)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/cookiegram_helper.rb
module CookiegramHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
require 'jwt'

module SessionsHelper

  def log_in(user)
    session[:user_id] = user.id
    cookies.permanent[:token] = create_token user.id
  end

  def log_out
    session.delete(:user_id)
    cookies.delete(:token)
    @current_user = nil
  end

  def current_user
    if session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
    elsif cookies[:token]
      token = verify_token(cookies[:token])
      if token && (user = User.find_by(id: token.id))
        log_in user
        @current_user = user
      else
        log_out
      end
    end
  end

  def is_logged_in?
    !current_user.nil?
  end

  def create_token(id)
    puts Cookiegram::Application.config.token_rsa_private
    JWT.encode({id: id}, Cookiegram::Application.config.token_rsa_private, 'RS256')
  end

  def verify_token(token)
    JWT.decode token, Cookiegram::Application.config.token_rsa_public, true, { algorithm: 'RS256' }
  end

end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.username, class: "gravatar")
  end
end

app/views/comments/_comment.html.erb
<div class="comment">
  <p class="comment-message"><%= comment.message %></p>
<!--  <p class="comment-username"><%#= comment.user.username %></p>-->
</div>

app/views/comments/_form.html.erb
<%= form_with(model: [ @post, @post.comments.build ], local: true) do |form| %>
  <%= form.text_area :message, placeholder: 'Message', class: "form-control" %>
  <%= form.submit "Add comment", class: "btn btn-primary" %>
<% end %>

app/views/cookiegram/index.html.erb
<h2>See what other cookiers are posting</h2>

<% @posts.each do |post| %>
  <%= render 'posts/post', post: post %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cookiegram</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!--[if lt IE 9]>
        <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js"></script>
    <![endif]-->
  </head>

  <body>
    <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <%= link_to '/', id: "logo", class: "navbar-brand" do %>
          <span class="cookie">🍪</span>
          cookiegram
        <% end %>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Home", '/' %></li>
<!--            <li><%#= link_to "Posts", '/posts' %></li>-->
            <li><%= link_to "Add post", new_post_path %></li>
            <% if is_logged_in? %>
              <li><%= link_to "Log out", logout_path, class: "btn btn-sm btn-secondary", method: :delete %></li>
              <li><%= link_to "Account", @current_user, class: "btn btn-sm btn-primary"%></li>
            <% else %>
              <li><%= link_to "Log in", '/login', class: "btn btn-sm btn-secondary" %></li>
              <li><%= link_to "Sign up", '/signup', class: "btn btn-sm btn-primary"%></li>
            <% end %>
          </ul>
        </nav>
      </div>
    </header>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: @post, local: true) do |form| %>

  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@post.errors.count, "error") %> prohibited
        this post from being saved:
      </h2>
      <ul>
        <% @post.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="col-md-6 col-md-offset-3">
        <%= form.label :description %>
        <%= form.text_area :description, class: 'form-control' %>

        <%= form.label :image %>
        <%= form.text_field :image, class: 'form-control' %>

        <%= form.submit "Add post", class: "btn btn-primary" %>
      <hr>
      <%= link_to 'Back', posts_path %>
    </div>
  </div>

<% end %>

app/views/posts/_post.html.erb
<div class="post-wrapper row">
  <div class="post col-md-6 col-md-offset-3">
    <%= link_to image_tag(post.image, class: 'post-image', alt: 'Cookie'), post %>
    <div class="post-content">
      <div class="post-content-header">
        <p>0 cookies</p>
        <p>Posted by <%= link_to post.user.username, post.user %></p>
      </div>
      <p class="post-description"><%= post.description %></p>
      <% if post.user == @current_user %>
        <td><%= link_to 'Show', post_path(post) %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post_path(post),
                        method: :delete,
                        data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </div>
  </div>
</div>

app/views/posts/edit.html.erb
<h1>Edit post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h2>List of posts</h2>

<% @posts.each do |post| %>
  <%= render 'posts/post', post: post %>
<% end %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

app/views/posts/show.html.erb
<%= render 'posts/post', post: @post %>
<div class="post-wrapper row">
  <div class="post col-md-6 col-md-offset-3">
    <div class="post-content">
      <h6>Comments</h6>
      <% @post.comments.each do |comment| %>
        <%= render 'comments/comment', comment: comment %>
      <% end %>
      <% if @post.comments.empty? %>
        <p>No comments yet.</p>
      <% end %>
      <br>
      <h6>Add a comment</h6>
      <%= render 'comments/form' %>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<h2>Edit profile</h2>

app/views/users/new.html.erb
  <% provide(:title, "Sign up") %>
  <h1>Sign up</h1>

  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <%= form_with(model: @user, local: true) do |form| %>

        <% if @user.errors.any? %>
          <div id="error_explanation">
            <h2>
              <%= pluralize(@user.errors.count, "error") %> prohibited this post from being saved:
            </h2>
            <ul>
              <% @user.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
        <% end %>

        <%= form.label :username %>
        <%= form.text_field :username, class: 'form-control' %>

        <%= form.label :email %>
        <%= form.email_field :email, class: 'form-control' %>

        <%= form.label :password %>
        <%= form.password_field :password, class: 'form-control' %>

        <%= form.submit "Log in", class: "btn btn-primary" %>
      <% end %>
      <hr>
      <p>Already have an account? <%= link_to "Log in", login_path %></p>
    </div>
  </div>

app/views/users/show.html.erb
<% if is_logged_in? %>
  <h2>User profile</h2>
  <div class="row">
    <div class="col-md-1 col-md-offset-3">
      <%= gravatar_for(@current_user) %>
    </div>
    <div class="col-md-5">
      <table class="table">
        <tr>
          <th>Username</th>
          <td><%= @current_user.username %></td>
        </tr>
        <tr>
          <th>Email</th>
          <td><%= @current_user.email %></td>
        </tr>
        <tr>
          <th>Joined</th>
          <td><%= @current_user.created_at %></td>
        </tr>
      </table>
    </div>
  </div>

  <h2>Your posts</h2>
  <% @user.posts.each do |post| %>
    <%= render 'posts/post', post: post %>
  <% end %>

<% else %>
  <h2>You are not logged in! Login first to see the content of this page.</h2>
<% end %>